### ISSUE TITLE
[Bug] Copper slabs behave incorrectly [1.20.1]

### ISSUE THREAD

**Issue by nexquin** [Enchanted-Games/enchanted-vertical-slabs#11]
**Describe the bug**
A) vertical copper slabs not able to be waxed in recipes. (Fig1)
B) waxed vertical copper slabs not able to be crafted from waxed cut copper blocks. (Fig2)
C) placed _waxed_ vertical copper slabs have slow mining breakage and drop nothing. (Fig3) Unwaxed vertical copper slabs break and drop as expected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch installation of modded minecraft 1.20.1 with Fabric-Loader-0.15.9-1.20.1.
2. Have or craft vanilla cut copper blocks and/or vanilla waxed cut copper blocks.
3. Attempt to craft vertical slabs from waxed blocks, see error.
4. Attempt to wax vertical slabs in crafting recipe, see error.
5. Place waxed vertical slab in world.
6. Attempt to break waxed vertical slab, see error.

**Expected behaviour**
A) vertical copper slabs able to be waxed in recipe like vanilla slabs can be.
B) waxed vertical copper slabs able to be crafted from waxed cut copper blocks like vanilla slabs can be.
C) placed waxed vertical copper slabs can be broken in same length of time as vanilla slabs and/or [unwaxed] vertical copper slabs, and drop themselves when broken like vanilla slabs and/or [unwaxed] vertical slabs do.

**Supporting content**
Fig1.1
![cant wax vertical slab](https://github.com/user-attachments/assets/622402d1-8e50-4d47-b155-a53546fd3895)
Fig1.2
![waxing vanilla slab](https://github.com/user-attachments/assets/eedd7a64-5ccf-451b-ba9d-a20294a5858d)
Fig2
![cant craft from waxed](https://github.com/user-attachments/assets/0e3693a6-682d-46bb-adfb-61351dbd3e52)
Fig3
https://github.com/user-attachments/assets/29404546-bfd7-43ff-b282-de6bd1f84641

**Environment**
 - Mod Version: initially crafted and placed with 1.9.1, noticed issues (especially dropping nothing) and updated to 1.9.1-patch1 (same issues)
 - Mod Loader: Fabric
 - Mod Loader Version: 0.15.9-1.20.1
 - Fabric Api Version: 0.92.1-1.20.1

**Comment by nexquin** [comment]
Please evaluate, and let me know if other information is needed--I've not had to submit a bug report before, patience is appreciated!

**Comment by Enchanted-Games** [comment]
thanks for the report, it has all the info i need!

as for fixing, I might just port v2.1.1 to 1.20.1, if its not too difficult, as its still a fairly popular version for mods

_(waxed copper slabs have been the bane of my existence lol)_

**Comment by Enchanted-Games** [comment]
just uploaded the [fix version to github](https://github.com/Enchanted-Games/enchanted-vertical-slabs/releases/tag/v2.2-backport1.20.1)! i'll close this issue once i've uploaded it to modrinth/curseforge etc for 1.20.1 and 1.21

**Comment by nexquin** [comment]
The fix version, using fabric loader 1.5.11 as required, has fixed the issues! The waxed vertical slabs are breaking and dropping as intended, vertical slabs can be made from waxed blocks, and vertical slabs can be waxed in the recipe table. 
(I won't close the issue for you, though, since you had a plan)
Thank you :)
