### ISSUE TITLE
[Feature Request] Combining different types of vertical slabs

### ISSUE THREAD

**Issue by Mipseldev** [Enchanted-Games/enchanted-vertical-slabs#14]
**Describe your feature request**
I was trying to build a window outline using the vertical slabs but found that you can not combine different slabs.

**Describe the solution you'd like**
It would be cool if support could be added to combine two different types of vertical slabs. I have provided images in the additional context section.

**Additional context**
Thank you for your time and for making such a cool mod!

![2024-08-23_04 26 15](https://github.com/user-attachments/assets/851174bd-9574-4664-b863-ee8fc650025d)
![2024-08-23_04 26 56](https://github.com/user-attachments/assets/320539a4-7f3b-4729-a452-a886308c99f6)
()

**Comment by Enchanted-Games** [comment]
this is already being tracked in #8, thanks for the feature request tho!
