### ISSUE TITLE
Unable to craft slabs in 1.21

### ISSUE THREAD

**Issue by NamelessYoungy** [Enchanted-Games/enchanted-vertical-slabs#4]
**Describe the bug**
Currently unable to craft the slabs in 1.21

**To Reproduce**
Steps to reproduce the behaviour:
1. Obtain oak planks
2. Place 3 in vertical alignment in a crafting table
3. Vertical slabs unable to be crafted

**Expected behaviour**
Should be able to craft the vertical slabs

**Additional content**

**Environment**
 - Mod Version: 1.21 (v2.0)
 - Mod Loader: fabric
 - Mod Loader Version: 0.15.11
 - Fabric Api Version: 0.100.1+1.21

**Comment by Enchanted-Games** [comment]
ah i forgot about the 1.21 datapack changes, ill fix this soon

**Comment by Enchanted-Games** [comment]
fixed in v2.0.1
