### ISSUE TITLE
[Bug] Uncraftable/ hard to break

### ISSUE THREAD

**Issue by TheWanderingTrader** [Enchanted-Games/enchanted-vertical-slabs#5]
**Describe the bug**
The slabs aren't appearing to be craftable in 1.21 as well as the game doesn't let you break them quickly with what you'd think the correct tool is.

**Environment**
 - Mod Version: 2.0.1
 - Mod Loader: fabric
 - Mod Loader Version: .15.11
 - Fabric Api Version: latest

**Comment by Enchanted-Games** [comment]
can you send the latest.log after opening a world with the mod enabled?

**Comment by TheWanderingTrader** [comment]
https://mclo.gs/15AKwUO

**Comment by Enchanted-Games** [comment]
you have enchanted vertical slabs 2.0.0 installed on the server, update it to 2.0.1

**Comment by TheWanderingTrader** [comment]
Thank you!

Kevin
Estonia

“The easiest path to take in life is never as rewarding as it is to
overcome hardship on a path with hurdles. Take chances and make the most of
your experiences”

**Comment by Enchanted-Games** [comment]
np!
