### ISSUE TITLE
[Crash] Version 2.0.1 crashes with Neoforge 21.0.46 on launch

### ISSUE THREAD

**Issue by ergooll** [Enchanted-Games/enchanted-vertical-slabs#7]
**Describe the crash**
Launching the game with Neoforge 21.0.46 and Enchanted Vertical Slabs 2.0.1 crashes the game on launch. Tested with other mods and only EVS mod installed on clean Neoforge install. I also tested other releases of Neoforge that crashed too, but 21.0.17 is stable and not crashing.

**Crash log**
[crash-2024-07-02_13.47.40-fml.txt](https://github.com/user-attachments/files/16066925/crash-2024-07-02_13.47.40-fml.txt)

**To Reproduce**
Steps to reproduce the crash:
1. install Minecraft 1.21 with Neoforge 21.0.46 (also tested several earlier versions that also crashed, 21.0.17 is stable at least) and EVS mod 2.0.1
2. Launch the game
3. Crash log

**Additional content**
If applicable, add screenshots / videos / logs to help explain the bug

**Environment**
 - Mod Version: 2.0.1
 - Mod Loader: Neoforge
 - Mod Loader Version: 21.0.46
 - Launcher: CurseForge

**Comment by Enchanted-Games** [comment]
fixed in v2.0.2
