### ISSUE TITLE
Waxed Cut Copper Blocks Don't Drop 

### ISSUE THREAD

**Issue by GenMode** [Enchanted-Games/enchanted-vertical-slabs#9]
Hi not to be a bother but I've noticed the waxed cut copper vertical slab variants don't seem to have loot table drops. Is this intentional? Since it seems to have persisted for a good number of updates. Thank you for your time and sorry for the bother

**Comment by Enchanted-Games** [comment]
Seems there’s no loot tables for waxed copper slabs anymore, not sure how / when that happened but I’ll get it fixed :)

**Comment by Enchanted-Games** [comment]
fixed in v2.1.1
